### PR TITLE
Ubuntu 16.04 Release Party in Beijing

### PR DESCRIPTION
**Pull request by bigeagle**
News for ubuntu 16.04  relase party in beijing

### CODE REVIEW

**Comment by lovenemesis** [comment]
Please add Time in 24H format to to Date attribute in Meta

e.g. Date: 2016-05-24 XX:XX:XX

**Comment by bigeagle** [comment]
@lovenemesis updated

**Comment by bigeagle** [comment]
Hi, I just received a notification from canonical that the first topic has changed. I'll update this PR later.

**Comment by bigeagle** [comment]
@lovenemesis  updated

**Comment by xuxiaodong** [comment]
Merged. Thanks.

**Pull request merged**
